import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Providers } from "@/provider/Provider";
import Header from "@/components/header/Header";
import { Toaster } from "react-hot-toast";
import { UserContextProvider } from "@/store/ContextProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            {/* <Header /> */}
            <UserContextProvider>
              <Toaster />
              {children}
            </UserContextProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
